/// Flutter icons AlertAppIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AlertAppIcons
///      fonts:
///       - asset: fonts/AlertAppIcons.ttf
///
/// 
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
///
import 'package:flutter/widgets.dart';

class AlertAppIcons {
  AlertAppIcons._();

  static const _kFontFam = 'AlertAppIcons';
  static const String? _kFontPkg = null;

  static const IconData aura = IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hand = IconData(0xe9f1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData player_pain = IconData(0xea6a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData player_shot = IconData(0xea6c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

final Map<int, dynamic> getMapIcon = {
  1 : AlertAppIcons.hand,
  2 : AlertAppIcons.player_shot,
  3 : AlertAppIcons.player_pain,
  4 : AlertAppIcons.aura,
};
